Formating: spaces to tabs and remove trailing whitespaces.

diff --git a/btrfs-subvolume-backup b/btrfs-subvolume-backup
--- a/btrfs-subvolume-backup
+++ b/btrfs-subvolume-backup
@@ -23,11 +23,11 @@ PROG=${0##*/}
 lock=/var/run/$PROG
 
 usage() {
-    cat <<EOF
-Usage: 
+	cat <<EOF
+Usage:
 cd /mnt/source_btrfs_pool
-$PROG	
-	[--init] 
+$PROG
+	[--init]
 	[--keep|-k num]
 	[--dest hostname] [--port|p 22]
 	[--diff]
@@ -36,16 +36,16 @@ $PROG
 	volume_name /mnt/backup_btrfs_pool
 
 Options:
-    --init:          Print this help message and exit.
-    --lockname|-l:   Override lockfile in /var/run: $PROG
-    --keep num:      Keep the last snapshots for local backups (5 by default)
-    --dest hostname: If present, ssh to that machine to make the copy.
-    --port|-p:       Port number for ssh (defaults to 22).
-    --postfix:	     postfix to add to snapshots
-    --bckrot:	     secondary set of snapshots to rotate out for that volume
+	--init:          Print this help message and exit.
+	--lockname|-l:   Override lockfile in /var/run: $PROG
+	--keep num:      Keep the last snapshots for local backups (5 by default)
+	--dest hostname: If present, ssh to that machine to make the copy.
+	--port|-p:       Port number for ssh (defaults to 22).
+	--postfix:	     postfix to add to snapshots
+	--bckrot:	     secondary set of snapshots to rotate out for that volume
     		     (if the copy succeeds, its own snapshot history replaces an
 		     out of band backup snapshot rotation).
-    --diff:	     show an approximate diff between the snapshots
+	--diff:	     show an approximate diff between the snapshots
 
 This will snapshot volume_name in a btrfs pool, and send the diff
 between it and the previous snapshot (volume_name.last) to another btrfs
@@ -54,31 +54,31 @@ pool (on other drives)
 If your backup destination is another machine, you'll need to add a few
 ssh commands this script
 
-The num snapshots to keep is to give snapshots you can recover data from 
+The num snapshots to keep is to give snapshots you can recover data from
 and they get deleted after num runs. Set to 0 to disable (one snapshot will
 be kept since it's required for the next diff to be computed).
 EOF
-    exit 0
+	exit 0
 }
 
 die () {
-    msg=${1:-}
-    # don't loop on ERR
-    trap '' ERR
+	msg=${1:-}
+	# don't loop on ERR
+	trap '' ERR
 
-    rm $lock
+	rm $lock
 
-    echo "$msg" >&2
-    echo >&2
+	echo "$msg" >&2
+	echo >&2
 
-    # This is a fancy shell core dumper
-    if echo $msg | grep -q 'Error line .* with status'; then
+	# This is a fancy shell core dumper
+	if echo $msg | grep -q 'Error line .* with status'; then
 	line=`echo $msg | sed 's/.*Error line \(.*\) with status.*/\1/'`
 	echo " DIE: Code dump:" >&2
 	nl -ba $0 | grep -5 "\b$line\b" >&2
-    fi
-    
-    exit 1
+	fi
+
+	exit 1
 }
 
 # Trap errors for logging before we die (so that they can be picked up
@@ -100,69 +100,69 @@ eval set -- $TEMP
 
 while :
 do
-    case "$1" in
-        -h|--help|--usage)
-            usage
-            shift
-            ;;
+	case "$1" in
+	-h|--help|--usage)
+		usage
+		shift
+		;;
 
 	--postfix)
-	    shift
-	    pf=_$1
-	    lock="$lock.$pf"
-	    shift
-	    ;;
+		shift
+		pf=_$1
+		lock="$lock.$pf"
+		shift
+		;;
 
 	--lockname|-l)
-	    shift
-	    lock="/var/run/$1"
-	    shift
-	    ;;
+		shift
+		lock="/var/run/$1"
+		shift
+		;;
 
 	--bckrot|-b)
-	    shift
-	    bckrot=_$1
-	    shift
-	    ;;
+		shift
+		bckrot=_$1
+		shift
+		;;
 
 	--port|-p)
-	    shift
-	    port=$1
-	    shift
-	    ;;
+		shift
+		port=$1
+		shift
+		;;
 
 	--keep|-k)
-	    shift
-	    keep=$1
-	    shift
-	    ;;
+		shift
+		keep=$1
+		shift
+		;;
 
 	--dest|-d)
-	    shift
-	    dest=$1
-	    shift
-	    ;;
+		shift
+		dest=$1
+		shift
+		;;
 
 	--init)
-	    init=1
-	    shift
-	    ;;
+		init=1
+		shift
+		;;
 
 	--diff)
-	    diff=1
-	    shift
-	    ;;
+		diff=1
+		shift
+		;;
 
 	--)
-	    shift
-	    break
-	    ;;
+		shift
+		break
+		;;
 
-        *) 
-	    echo "Internal error from getopt!"
-	    exit 1
-	    ;;
-    esac
+	*)
+		echo "Internal error from getopt!"
+		exit 1
+		;;
+	esac
 done
 [[ $keep < 1 ]] && die "Must keep at least one snapshot for things to work ($keep given)"
 [[ "$dest" != localhost ]] && ssh="ssh -p$port $dest"
@@ -185,14 +185,14 @@ bckrot=${bckrot:-${pf}_ro}
 # create lock
 exec 200>$lock
 if ! flock -n 200; then
-    echo "$lock held for $PROG, quitting" >&2
-    exit
+	echo "$lock held for $PROG, quitting" >&2
+	exit
 fi
 
 if [[ -z "$init" ]]; then
-    test -e "${vol}${pf}_last" \
-	|| die "Cannot sync $vol, ${vol}${pf}_last missing. Try --init?"
-    src_snap="$(readlink -e ${vol}${pf}_last)"
+	test -e "${vol}${pf}_last" \
+			|| die "Cannot sync $vol, ${vol}${pf}_last missing. Try --init?"
+	src_snap="$(readlink -e ${vol}${pf}_last)"
 fi
 src_newsnap="${vol}${pf}_ro.$DATE"
 src_newsnaprw="${vol}${pf}_rw.$DATE"
@@ -202,8 +202,8 @@ $ssh test -d "$dest_pool/" || die "ABORT: $dest_pool not a directory (on $dest)"
 btrfs subvolume snapshot -r "$vol" "$src_newsnap"
 
 if [[ -n "$diff" ]]; then
-    echo diff between "$src_snap" "$src_newsnap"
-    btrfs-diff "$src_snap" "$src_newsnap"
+	echo diff between "$src_snap" "$src_newsnap"
+	btrfs-diff "$src_snap" "$src_newsnap"
 fi
 
 # There is currently an issue that the snapshots to be used with "btrfs send"
@@ -213,18 +213,18 @@ sync
 
 failed=""
 if [[ -n "$init" ]]; then
-    ionice -c3 btrfs send "$src_newsnap" | $ssh ionice -c3 btrfs receive "$dest_pool/" || failed=1
+	ionice -c3 btrfs send "$src_newsnap" | $ssh ionice -c3 btrfs receive "$dest_pool/" || failed=1
 else
-    #echo "$src_snap" "$src_newsnap"
-    ionice -c3 btrfs send -p "$src_snap" "$src_newsnap" | $ssh ionice -c3 btrfs receive "$dest_pool/"\
-	|| failed=1
+	#echo "$src_snap" "$src_newsnap"
+	ionice -c3 btrfs send -p "$src_snap" "$src_newsnap" | $ssh ionice -c3 btrfs receive "$dest_pool/"\
+			|| failed=1
 fi
 if [[ -n "$failed" ]]; then
-    echo >&2
-    echo "ABORT: btrfs send -p ${src_snap:-} $src_newsnap | $ssh btrfs receive $dest_pool/ failed" >&2
-    btrfs subvolume delete "$src_newsnap" | grep -v 'Transaction commit:'
-    $ssh btrfs subvolume delete "$dest_pool/$src_newsnap" | grep -v 'Transaction commit:'
-    exit 1
+	echo >&2
+	echo "ABORT: btrfs send -p ${src_snap:-} $src_newsnap | $ssh btrfs receive $dest_pool/ failed" >&2
+	btrfs subvolume delete "$src_newsnap" | grep -v 'Transaction commit:'
+	$ssh btrfs subvolume delete "$dest_pool/$src_newsnap" | grep -v 'Transaction commit:'
+	exit 1
 fi
 
 # We make a read-write snapshot in case you want to use it for a chroot
@@ -248,38 +248,38 @@ $ssh ln -snf $src_newsnaprw $dest_pool/${vol}${pf}_last_rw
 # a literal 'volname_daily.*' should none exist.
 shopt -s nullglob
 ls -rd ${vol}${pf}_ro.* ${vol}${bckrot}.* | sort -u | sort -r -t. -k2 | \
-       	tail -n +$(( $keep + 1 ))| while read snap
+		tail -n +$(( $keep + 1 ))| while read snap
 do
-    # Debugging
-    #echo btrfs subvolume delete "$snap"
-    btrfs subvolume delete "$snap" | grep -v 'Transaction commit:'
+	# Debugging
+	#echo btrfs subvolume delete "$snap"
+	btrfs subvolume delete "$snap" | grep -v 'Transaction commit:'
 done
 ls -rd ${vol}${pf}_rw.* | tail -n +$(( $keep + 1 ))| while read snap
 do
-    btrfs subvolume delete "$snap" | grep -v 'Transaction commit:'
+	btrfs subvolume delete "$snap" | grep -v 'Transaction commit:'
 done
 
 # Same thing for destination (assume the same number of snapshots to keep,
 # you can change this if you really want).
 
 if [[ -z "$ssh" ]]; then
-    for snap in $(ls -rd $dest_pool/${vol}${pf}_ro* | tail -n +$(( $keep + 1 )))
-    do
+	for snap in $(ls -rd $dest_pool/${vol}${pf}_ro* | tail -n +$(( $keep + 1 )))
+	do
 	btrfs subvolume delete "$snap" | grep -v 'Transaction commit:'
-    done
-    for snap in $(ls -rd $dest_pool/${vol}${pf}_rw* | tail -n +$(( $keep + 1 )))
-    do
+	done
+	for snap in $(ls -rd $dest_pool/${vol}${pf}_rw* | tail -n +$(( $keep + 1 )))
+	do
 	btrfs subvolume delete "$snap" | grep -v 'Transaction commit:'
-    done
+	done
 else
-    for snap in $($ssh ls -rd $dest_pool/${vol}${pf}_'ro*' | tail -n +$(( $keep + 1 )))
-    do
+	for snap in $($ssh ls -rd $dest_pool/${vol}${pf}_'ro*' | tail -n +$(( $keep + 1 )))
+	do
 	$ssh btrfs subvolume delete "$snap" | grep -v 'Transaction commit:'
-    done
-    for snap in $($ssh ls -rd $dest_pool/${vol}${pf}_'rw*' | tail -n +$(( $keep + 1 )))
-    do
+	done
+	for snap in $($ssh ls -rd $dest_pool/${vol}${pf}_'rw*' | tail -n +$(( $keep + 1 )))
+	do
 	$ssh btrfs subvolume delete "$snap" | grep -v 'Transaction commit:'
-    done
+	done
 fi
 
 rm $lock
